import { Injectable } from '@angular/core';
import { foods } from 'src/app/shared/Models/food';
@Injectable({
  providedIn: 'root',
})
export class FoodService {
  constructor() {}
  getAll(): foods[] {
    return [
      {
        id: 1,
        name: 'Pizza Peproni',
        cookTime: '10-20',
        price: 10,
        favorite: false,
        origins: ['italy'],
        star: 4.5,
        imageUrl: '/assets/1.jfif',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
      },
      {
        id: 2,
        name: 'Meatball',
        cookTime: '10-20',
        price: 20,
        favorite: true,
        origins: ['italy', 'Middle east', 'china'],
        star: 4.7,
        imageUrl: '/assets/1.jfif',
        tags: ['Slowfood', 'Lunch'],
      },
      {
        id: 3,
        name: 'Hamburger',
        cookTime: '10-20',
        price: 15,
        favorite: true,
        origins: ['italy', 'uk', 'middle east'],
        star: 4.5,
        imageUrl: '/assets/1.jfif',
        tags: ['Fastfood', 'hamburger'],
      },
      {
        id: 4,
        name: 'Chicken Soup',
        cookTime: '15-30',
        price: 35,
        favorite: false,
        origins: ['italy', 'asia'],
        star: 4.5,
        imageUrl: '/assets/1.jfif',
        tags: ['slowfood', 'soup'],
      },
      {
        id: 5,
        name: 'fried potatos',
        cookTime: '10-20',
        price: 10,
        favorite: true,
        origins: ['italy', 'asia'],
        star: 4.5,
        imageUrl: '/assets/1.jfif',
        tags: ['Fastfood', 'fry'],
      },
      {
        id: 6,
        name: 'vegetable Pizza',
        cookTime: '10-20',
        price: 50,
        favorite: false,
        origins: ['italy'],
        star: 4.5,
        imageUrl: '/assets/1.jfif',
        tags: ['Fastfood', 'Pizza', 'Lunch'],
      },
      {
        id: 7,
        name: 'shawarma',
        cookTime: '10-20',
        price: 3,
        favorite: false,
        origins: ['italy'],
        star: 4.5,
        imageUrl: '/assets/1.jfif',
        tags: ['Fastfood', 'shawarma'],
      },
      {
        id: 8,
        name: 'Kabab',
        cookTime: '10-20',
        price: 10,
        favorite: true,
        origins: ['italy'],
        star: 4.5,
        imageUrl: '/assets/1.jfif',
        tags: ['slowfood', 'Kabab'],
      },
      // {
      //   id: 9,
      //   name: 'smash burger',
      //   cookTime: '10-20',
      //   price: 45,
      //   favorite: false,
      //   origins: ['us'],
      //   star: 4.5,
      //   imageUrl: '/assets/1.jfif',
      //   tags: ['Fastfood', 'smashburger'],
      // },
    ];
  }
}
